# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_choose_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_db_choose_class(object):
    def setupUi(self, db_choose_class):
        db_choose_class.setObjectName("db_choose_class")
        db_choose_class.setWindowModality(QtCore.Qt.WindowModal)
        db_choose_class.resize(441, 368)
        self.form_frame = QtWidgets.QFrame(db_choose_class)
        self.form_frame.setGeometry(QtCore.QRect(10, 10, 391, 331))
        self.form_frame.setStyleSheet("border: 1px solid black; border-radius: 10px;")
        self.form_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.form_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_frame.setObjectName("form_frame")
        self.main_label = QtWidgets.QLabel(self.form_frame)
        self.main_label.setGeometry(QtCore.QRect(130, 10, 111, 16))
        self.main_label.setStyleSheet("border-style: none;")
        self.main_label.setTextFormat(QtCore.Qt.PlainText)
        self.main_label.setWordWrap(False)
        self.main_label.setIndent(0)
        self.main_label.setOpenExternalLinks(False)
        self.main_label.setObjectName("main_label")
        self.sqlite_frame = QtWidgets.QFrame(self.form_frame)
        self.sqlite_frame.setGeometry(QtCore.QRect(20, 70, 351, 41))
        self.sqlite_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sqlite_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sqlite_frame.setObjectName("sqlite_frame")
        self.path_label = QtWidgets.QLabel(self.sqlite_frame)
        self.path_label.setGeometry(QtCore.QRect(10, 10, 41, 16))
        self.path_label.setStyleSheet("border-style: none;")
        self.path_label.setObjectName("path_label")
        self.path_edit = QtWidgets.QLineEdit(self.sqlite_frame)
        self.path_edit.setEnabled(False)
        self.path_edit.setGeometry(QtCore.QRect(60, 10, 241, 21))
        self.path_edit.setStyleSheet("border-radius: 0px")
        self.path_edit.setObjectName("path_edit")
        self.pushButton = QtWidgets.QPushButton(self.sqlite_frame)
        self.pushButton.setGeometry(QtCore.QRect(310, 10, 31, 23))
        self.pushButton.setObjectName("pushButton")
        self.postgres_frame = QtWidgets.QFrame(self.form_frame)
        self.postgres_frame.setGeometry(QtCore.QRect(20, 120, 351, 161))
        self.postgres_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.postgres_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.postgres_frame.setObjectName("postgres_frame")
        self.bd_name_lbl = QtWidgets.QLabel(self.postgres_frame)
        self.bd_name_lbl.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.bd_name_lbl.setStyleSheet("border-style: none;")
        self.bd_name_lbl.setIndent(-1)
        self.bd_name_lbl.setObjectName("bd_name_lbl")
        self.user_name_lbl = QtWidgets.QLabel(self.postgres_frame)
        self.user_name_lbl.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.user_name_lbl.setStyleSheet("border-style: none;")
        self.user_name_lbl.setObjectName("user_name_lbl")
        self.pssword_name_lbl = QtWidgets.QLabel(self.postgres_frame)
        self.pssword_name_lbl.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.pssword_name_lbl.setStyleSheet("border-style: none;")
        self.pssword_name_lbl.setObjectName("pssword_name_lbl")
        self.host_name_lbl = QtWidgets.QLabel(self.postgres_frame)
        self.host_name_lbl.setGeometry(QtCore.QRect(10, 100, 47, 13))
        self.host_name_lbl.setStyleSheet("border-style: none;")
        self.host_name_lbl.setObjectName("host_name_lbl")
        self.port_name_lbl = QtWidgets.QLabel(self.postgres_frame)
        self.port_name_lbl.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.port_name_lbl.setStyleSheet("border-style: none;")
        self.port_name_lbl.setObjectName("port_name_lbl")
        self.bd_name_edit = QtWidgets.QLineEdit(self.postgres_frame)
        self.bd_name_edit.setEnabled(True)
        self.bd_name_edit.setGeometry(QtCore.QRect(110, 10, 231, 21))
        self.bd_name_edit.setStyleSheet("border-radius: 0px")
        self.bd_name_edit.setObjectName("bd_name_edit")
        self.user_name_edit = QtWidgets.QLineEdit(self.postgres_frame)
        self.user_name_edit.setGeometry(QtCore.QRect(110, 40, 231, 21))
        self.user_name_edit.setStyleSheet("border-radius: 0px")
        self.user_name_edit.setObjectName("user_name_edit")
        self.pssword_name_edit = QtWidgets.QLineEdit(self.postgres_frame)
        self.pssword_name_edit.setGeometry(QtCore.QRect(110, 70, 231, 21))
        self.pssword_name_edit.setStyleSheet("border-radius: 0px")
        self.pssword_name_edit.setObjectName("pssword_name_edit")
        self.host_name_edit = QtWidgets.QLineEdit(self.postgres_frame)
        self.host_name_edit.setGeometry(QtCore.QRect(110, 100, 231, 21))
        self.host_name_edit.setStyleSheet("border-radius: 0px")
        self.host_name_edit.setObjectName("host_name_edit")
        self.port_name_edit = QtWidgets.QLineEdit(self.postgres_frame)
        self.port_name_edit.setGeometry(QtCore.QRect(110, 130, 231, 21))
        self.port_name_edit.setStyleSheet("border-radius: 0px;\n"
"width: 1800;")
        self.port_name_edit.setObjectName("port_name_edit")
        self.save_btn = QtWidgets.QPushButton(self.form_frame)
        self.save_btn.setEnabled(False)
        self.save_btn.setGeometry(QtCore.QRect(80, 290, 97, 27))
        self.save_btn.setStyleSheet("border-radius: 4px;\n"
"height: 25px;")
        self.save_btn.setObjectName("save_btn")
        self.cancel_btn = QtWidgets.QPushButton(self.form_frame)
        self.cancel_btn.setGeometry(QtCore.QRect(190, 290, 111, 27))
        self.cancel_btn.setStyleSheet("border-radius: 4px;\n"
"height: 25px")
        self.cancel_btn.setObjectName("cancel_btn")
        self.radio_button_1 = QtWidgets.QRadioButton(self.form_frame)
        self.radio_button_1.setGeometry(QtCore.QRect(70, 40, 82, 17))
        self.radio_button_1.setStyleSheet("border-style: none;")
        self.radio_button_1.setObjectName("radio_button_1")
        self.radio_button_2 = QtWidgets.QRadioButton(self.form_frame)
        self.radio_button_2.setGeometry(QtCore.QRect(220, 40, 82, 17))
        self.radio_button_2.setStyleSheet("border-style: none;")
        self.radio_button_2.setObjectName("radio_button_2")

        self.retranslateUi(db_choose_class)
        QtCore.QMetaObject.connectSlotsByName(db_choose_class)

    def retranslateUi(self, db_choose_class):
        _translate = QtCore.QCoreApplication.translate
        db_choose_class.setWindowTitle(_translate("db_choose_class", "Form"))
        self.main_label.setText(_translate("db_choose_class", "Выберите формат БД"))
        self.path_label.setText(_translate("db_choose_class", "Путь:"))
        self.pushButton.setText(_translate("db_choose_class", "..."))
        self.bd_name_lbl.setText(_translate("db_choose_class", "Имя БД:"))
        self.user_name_lbl.setText(_translate("db_choose_class", "Пользователь:"))
        self.pssword_name_lbl.setText(_translate("db_choose_class", "Пароль:"))
        self.host_name_lbl.setText(_translate("db_choose_class", "Хост:"))
        self.port_name_lbl.setText(_translate("db_choose_class", "Порт:"))
        self.save_btn.setText(_translate("db_choose_class", "Сохранить"))
        self.cancel_btn.setText(_translate("db_choose_class", "Отмена"))
        self.radio_button_1.setText(_translate("db_choose_class", "SQLite"))
        self.radio_button_2.setText(_translate("db_choose_class", "PostgreSQL"))

